<?php

declare(strict_types=1);

namespace App\Update;

/**
 * The public keys this installation accepts release signatures from.
 *
 * BUILT_IN is the project's trust root, and it is EMPTY on purpose until the
 * project's release key exists: the private half must be generated by the
 * person who will make releases and kept by them, off every server and out
 * of this repository (docs/updates/RELEASES.md, "De releasesleutel"). Then
 * its public half goes here, and every release from that one on trusts it.
 *
 * MYGDALA_UPDATE_PUBLIC_KEY (UpdateConfig) REPLACES the built-in list rather
 * than adding to it: a distribution that runs its own feed signs with its
 * own key, and should not keep trusting a key it does not control. Setting
 * that variable needs access to .env, which already means full control of
 * the installation, so it opens no door that was closed.
 */
final class ReleaseKeys
{
    /** @var list<string> base64 Ed25519 public keys */
    private const BUILT_IN = [];

    /**
     * @return array<string, string> key id => raw 32-byte public key; an
     *                               unusable configured key yields []
     */
    public static function trusted(): array
    {
        $configured = UpdateConfig::publicKey();
        $encoded = $configured !== '' ? [$configured] : self::BUILT_IN;

        $keys = [];
        foreach ($encoded as $candidate) {
            $raw = base64_decode($candidate, true);

            if ($raw === false || strlen($raw) !== 32) {
                error_log('[ReleaseKeys] ignoring a release public key that is not 32 bytes of base64');
                continue;
            }

            $keys[ReleaseSignature::keyId($raw)] = $raw;
        }

        return $keys;
    }
}
